//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchLocationXamarinApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CountryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CountryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SearchLocationXamarinApp.Resources.CountryResource", typeof(CountryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api error.
        /// </summary>
        internal static string ApiErrorTitle {
            get {
                return ResourceManager.GetString("ApiErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO!.
        /// </summary>
        internal static string ButtonGo {
            get {
                return ResourceManager.GetString("ButtonGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check database content....
        /// </summary>
        internal static string CheckdbText {
            get {
                return ResourceManager.GetString("CheckdbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries downloaded correctly!....
        /// </summary>
        internal static string CountriesDownloadedText {
            get {
                return ResourceManager.GetString("CountriesDownloadedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading countries and additional information....
        /// </summary>
        internal static string DownloadingInfoText {
            get {
                return ResourceManager.GetString("DownloadingInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to query the API....
        /// </summary>
        internal static string FailedQueryAPIText {
            get {
                return ResourceManager.GetString("FailedQueryAPIText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information saved on the device correctly!....
        /// </summary>
        internal static string InformationSavedText {
            get {
                return ResourceManager.GetString("InformationSavedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load information.
        /// </summary>
        internal static string LoadInformationTitle {
            get {
                return ResourceManager.GetString("LoadInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to query the API, please check the AppConfig credentials.
        /// </summary>
        internal static string MsgFailedQueryAPI {
            get {
                return ResourceManager.GetString("MsgFailedQueryAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At this moment the necessary information is being loaded, please wait a moment.
        /// </summary>
        internal static string MsgInfoLoaded {
            get {
                return ResourceManager.GetString("MsgInfoLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information has been saved on the device.
        /// </summary>
        internal static string MsgInfoSaved {
            get {
                return ResourceManager.GetString("MsgInfoSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved information.
        /// </summary>
        internal static string SavedInformationTitle {
            get {
                return ResourceManager.GetString("SavedInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Search for a country!.
        /// </summary>
        internal static string SearchControlText {
            get {
                return ResourceManager.GetString("SearchControlText", resourceCulture);
            }
        }
    }
}
